/**
 * 月度结余相关类型定义
 * 用于记录每月末的库存结余情况，支持FIFO批次管理
 */

import { BaseEntity } from './entities';

// =============== 月度结余核心实体 ===============

/**
 * 月度结余记录
 * 记录每月末各批次的库存结余情况
 */
export interface MonthlyBalance extends BaseEntity {
  balanceDate: Date;                // 结余日期（月末）
  year: number;                     // 年份
  month: number;                    // 月份
  productId: string;                // 产品ID
  productName: string;              // 产品名称
  productSku: string;               // 产品SKU
  categoryId: string;               // 分类ID
  categoryName: string;             // 分类名称
  warehouseId: string;              // 仓库ID
  warehouseName: string;            // 仓库名称
  unitId: string;                   // 单位ID
  unitName: string;                 // 单位名称
  unitSymbol: string;               // 单位符号
  
  // 批次信息（支持FIFO）
  batchId: string;                  // 批次ID
  batchNo: string;                  // 批次号
  inboundDate: Date;                // 入库日期
  supplierBatchNo?: string;         // 供应商批次号
  
  // 数量和金额
  remainingQuantity: number;        // 剩余数量
  unitCost: number;                 // 单位成本
  totalValue: number;               // 总价值 (remainingQuantity × unitCost)
  
  // 附加信息
  expiryDate?: Date;                // 过期日期
  batchAge: number;                 // 批次年龄（天数）
  
  // 状态
  status: MonthlyBalanceStatus;     // 结余状态
  
  // 审计信息
  generatedBy: string;              // 生成人
  generatedAt: Date;                // 生成时间
  isAutoGenerated: boolean;         // 是否自动生成
  remark?: string;                  // 备注
}

/**
 * 月度结余状态枚举
 */
export enum MonthlyBalanceStatus {
  ACTIVE = 'active',                // 正常
  EXPIRED = 'expired',              // 已过期
  ADJUSTED = 'adjusted',            // 已调整
  ARCHIVED = 'archived'             // 已归档
}

/**
 * 月度结余汇总
 * 按产品、仓库等维度汇总的月度结余信息
 */
export interface MonthlyBalanceSummary {
  year: number;                     // 年份
  month: number;                    // 月份
  balanceDate: Date;                // 结余日期
  
  // 按产品汇总
  productSummary: {
    productId: string;
    productName: string;
    productSku: string;
    categoryName: string;
    unitName: string;
    unitSymbol: string;
    totalQuantity: number;          // 总数量
    totalValue: number;             // 总价值
    batchCount: number;             // 批次数量
    avgUnitCost: number;            // 平均单位成本
    oldestBatchDate: Date;          // 最老批次日期
    newestBatchDate: Date;          // 最新批次日期
    avgBatchAge: number;            // 平均批次年龄
    expiredBatchCount: number;      // 过期批次数量
    expiredQuantity: number;        // 过期数量
    expiredValue: number;           // 过期价值
  }[];
  
  // 按仓库汇总
  warehouseSummary: {
    warehouseId: string;
    warehouseName: string;
    totalValue: number;             // 总价值
    productCount: number;           // 产品种类数
    batchCount: number;             // 批次数量
    avgBatchAge: number;            // 平均批次年龄
  }[];
  
  // 按分类汇总
  categorySummary: {
    categoryId: string;
    categoryName: string;
    totalValue: number;             // 总价值
    productCount: number;           // 产品种类数
    batchCount: number;             // 批次数量
  }[];
  
  // 总计
  totals: {
    totalValue: number;             // 总价值
    totalQuantity: number;          // 总数量（不同单位无法直接相加，仅作参考）
    productCount: number;           // 产品种类数
    batchCount: number;             // 批次数量
    expiredBatchCount: number;      // 过期批次数量
    expiredValue: number;           // 过期价值
  };
}

// =============== 月度结余生成参数 ===============

/**
 * 月度结余生成参数
 */
export interface MonthlyBalanceGenerateParams {
  year: number;                     // 年份
  month: number;                    // 月份
  warehouseIds?: string[];          // 仓库ID列表（可选，不指定则生成所有仓库）
  productIds?: string[];            // 产品ID列表（可选，不指定则生成所有产品）
  categoryIds?: string[];           // 分类ID列表（可选，不指定则生成所有分类）
  includeZeroStock?: boolean;       // 是否包含零库存（默认false）
  includeExpired?: boolean;         // 是否包含过期批次（默认true）
  operator: string;                 // 操作人
  remark?: string;                  // 备注
}

/**
 * 月度结余查询参数
 */
export interface MonthlyBalanceQueryParams {
  year?: number;                    // 年份
  month?: number;                   // 月份
  startDate?: Date;                 // 开始日期
  endDate?: Date;                   // 结束日期
  productId?: string;               // 产品ID
  warehouseId?: string;             // 仓库ID
  categoryId?: string;              // 分类ID
  status?: MonthlyBalanceStatus;    // 状态
  includeExpired?: boolean;         // 是否包含过期
  minValue?: number;                // 最小价值
  maxValue?: number;                // 最大价值
  batchNoPattern?: string;          // 批次号模式匹配
  
  // 排序参数
  sortBy?: 'balanceDate' | 'productName' | 'totalValue' | 'batchAge' | 'inboundDate';
  sortOrder?: 'asc' | 'desc';
  
  // 分页参数
  page?: number;
  pageSize?: number;
}

// =============== 月度结余统计分析 ===============

/**
 * 月度结余统计信息
 */
export interface MonthlyBalanceStatistics {
  period: {
    year: number;
    month: number;
    balanceDate: Date;
  };
  
  // 基础统计
  basic: {
    totalRecords: number;           // 总记录数
    totalProducts: number;          // 产品种类数
    totalBatches: number;           // 批次数量
    totalValue: number;             // 总价值
    avgBatchValue: number;          // 平均批次价值
  };
  
  // 年龄分析
  ageAnalysis: {
    ranges: {
      range: string;                // 年龄范围（如 "0-30天"）
      batchCount: number;           // 批次数量
      totalQuantity: number;        // 总数量
      totalValue: number;           // 总价值
      percentage: number;           // 占比
    }[];
    avgAge: number;                 // 平均年龄
    oldestBatch: {
      batchId: string;
      batchNo: string;
      age: number;
      productName: string;
      quantity: number;
      value: number;
    } | null;
  };
  
  // 价值分析
  valueAnalysis: {
    topProducts: {
      productId: string;
      productName: string;
      totalValue: number;
      batchCount: number;
      percentage: number;
    }[];
    topWarehouses: {
      warehouseId: string;
      warehouseName: string;
      totalValue: number;
      batchCount: number;
      percentage: number;
    }[];
    topCategories: {
      categoryId: string;
      categoryName: string;
      totalValue: number;
      batchCount: number;
      percentage: number;
    }[];
  };
  
  // 过期分析
  expiryAnalysis: {
    expiredBatches: number;         // 过期批次数
    expiredValue: number;           // 过期价值
    expiredPercentage: number;      // 过期占比
    soonToExpire: {                 // 即将过期（30天内）
      batchCount: number;
      totalValue: number;
      percentage: number;
    };
  };
  
  // 周转分析
  turnoverAnalysis: {
    slowMoving: {                   // 滞销品（批次年龄>90天）
      batchCount: number;
      totalValue: number;
      percentage: number;
    };
    deadStock: {                    // 死库存（批次年龄>365天）
      batchCount: number;
      totalValue: number;
      percentage: number;
    };
  };
}

/**
 * 月度结余对比分析
 */
export interface MonthlyBalanceComparison {
  currentPeriod: {
    year: number;
    month: number;
    balanceDate: Date;
  };
  
  previousPeriod: {
    year: number;
    month: number;
    balanceDate: Date;
  };
  
  comparison: {
    totalValue: {
      current: number;
      previous: number;
      change: number;
      changePercentage: number;
    };
    
    batchCount: {
      current: number;
      previous: number;
      change: number;
      changePercentage: number;
    };
    
    productCount: {
      current: number;
      previous: number;
      change: number;
      changePercentage: number;
    };
    
    avgBatchAge: {
      current: number;
      previous: number;
      change: number;
      changePercentage: number;
    };
  };
  
  // 产品级别对比
  productComparison: {
    productId: string;
    productName: string;
    current: {
      totalValue: number;
      batchCount: number;
      avgAge: number;
    };
    previous: {
      totalValue: number;
      batchCount: number;
      avgAge: number;
    };
    changes: {
      valueChange: number;
      valueChangePercentage: number;
      batchCountChange: number;
      ageChange: number;
    };
  }[];
}

// =============== 月度结余导出格式 ===============

/**
 * 月度结余导出记录
 */
export interface MonthlyBalanceExportRecord {
  结余日期: string;                  // 格式化的结余日期
  年份: number;
  月份: number;
  产品编码: string;
  产品名称: string;
  分类: string;
  仓库: string;
  单位: string;
  批次号: string;
  入库日期: string;                  // 格式化的入库日期
  供应商批次号: string;
  剩余数量: number;
  单位成本: number;
  总价值: number;
  批次年龄: number;
  过期日期: string;                  // 格式化的过期日期
  状态: string;
  备注: string;
}

/**
 * 月度结余导出参数
 */
export interface MonthlyBalanceExportParams {
  queryParams: MonthlyBalanceQueryParams;
  exportFormat: 'xlsx' | 'csv' | 'pdf';
  fileName?: string;
  includeCharts?: boolean;           // 是否包含图表（PDF格式）
  groupBy?: 'product' | 'warehouse' | 'category' | 'batch'; // 分组方式
  includeSummary?: boolean;          // 是否包含汇总信息
  customColumns?: string[];          // 自定义列
}

// =============== 操作结果类型 ===============

/**
 * 月度结余操作结果
 */
export interface MonthlyBalanceOperationResult<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  warnings?: string[];
  summary?: {
    totalRecords: number;
    processedRecords: number;
    errorRecords: number;
    processingTime: number;
  };
}

/**
 * 月度结余生成结果
 */
export interface MonthlyBalanceGenerateResult {
  success: boolean;
  generatedRecords: number;
  totalValue: number;
  batchCount: number;
  productCount: number;
  warehouseCount: number;
  processingTime: number;
  errors?: string[];
  warnings?: string[];
  summary: MonthlyBalanceSummary;
}